[package]
name        = "scope-graphs"
description = "test"
version     = "0.1.0"
flix        = "0.56.0"
authors     = ["John Doe <john@example.com>"]

[mvn-dependencies]
"org.eclipse.lsp4j:org.eclipse.lsp4j" = "0.24.0"
"org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc" = "0.24.0"
